(function (global) {
  const VA = (global.VerbaAthanor = global.VerbaAthanor || {});

  const ANALYSES = {
    信じられない: {
      demo: true,
      word: '信じられない',
      lemma: '信じられない',
      ipa: 'しんじられない',
      pos: 'v',
      gender: '',
      glossZh: '難以置信；無法相信',
      glossFr: '信じることができない',
      alchNoteZh: '「相信」之根被可能與否定兩重封印：信而不能信。',
      firstAttested: {
        year: '近代',
        era: 'ModJ',
        form: '信じられない',
        whereZh: '現代日本語口語；語根 信ず 見於上代',
        sourceZh: '',
        author: '',
        work: '',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_shinji',
          surface: '信じ',
          kind: 'stem',
          meaningZh: '相信',
          meaningFr: '信じる',
          origin: 'Native',
          originForm: '信ず',
          noteZh: '和語動詞語幹。漢字「信」為義訓。',
        },
        {
          id: 'm_rare',
          surface: 'られ',
          kind: 'infl',
          meaningZh: '可能／被動',
          meaningFr: '可能・受身',
          origin: 'Native',
          originForm: 'られる',
          noteZh: '一段可能助動詞。',
        },
        {
          id: 'm_nai',
          surface: 'ない',
          kind: 'infl',
          meaningZh: '否定',
          meaningFr: '打消し',
          origin: 'Native',
          originForm: 'ない',
          noteZh: '否定助動詞。',
        },
      ],
      path: [
        {
          era: 'OJ',
          lang: 'OJ',
          form: '信ず',
          glossZh: '相信（古）',
          via: 'inherit',
          noteZh: '上代／文語 信ず。漢字「信」為義訓，語根是和語。',
          certainty: 'certain',
        },
        {
          era: 'MidJ',
          lang: 'MidJ',
          form: '信ずる',
          glossZh: '相信',
          via: 'inherit',
          noteZh: '中世日本語可見 信ずる；後來一段化為 信じる。',
          certainty: 'certain',
        },
        {
          era: 'ModJ',
          lang: 'ModJ',
          form: '信じる',
          glossZh: '相信',
          via: 'inherit',
          noteZh: '現代辭書形。語幹 信じ- 加可能 られ 與否定 ない。',
          certainty: 'certain',
        },
        {
          era: 'ModJ',
          lang: 'ModJ',
          form: '信じられない',
          glossZh: '無法相信',
          via: 'inherit',
          noteZh: '可能助動詞＋否定：信而不能信。',
          certainty: 'certain',
        },
      ],
      example: { fr: '信じられない話だ。', zh: '真是難以置信的事。' },
    },
    雨傘: {
      demo: true,
      word: '雨傘',
      lemma: '雨傘',
      ipa: 'あまがさ',
      pos: 'n',
      gender: '',
      glossZh: '雨傘',
      glossFr: '雨を防ぐ傘',
      alchNoteZh: '「雨」與「傘」合劑：擋雨之蓋。連濁成 あまがさ。',
      firstAttested: {
        year: '室町',
        era: 'MidJ',
        form: '雨傘',
        whereZh: '日本中世文獻',
        sourceZh: '',
        author: '',
        work: '',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_ame',
          surface: '雨',
          kind: 'han',
          meaningZh: '雨',
          meaningFr: 'あめ／あま',
          origin: 'Native',
          originForm: 'あめ',
          noteZh: '和語。複合時用 あま，連濁。',
        },
        {
          id: 'm_kasa',
          surface: '傘',
          kind: 'han',
          meaningZh: '傘、遮蓋',
          meaningFr: 'かさ',
          origin: 'Sino',
          originForm: '傘',
          noteZh: '漢字「傘」。連濁為 がさ。',
        },
      ],
      path: [
        { era: 'MidJ', lang: 'MidJ', form: '雨笠／雨傘', glossZh: '擋雨之蓋' },
        { era: 'ModJ', lang: 'ModJ', form: '雨傘', glossZh: '雨傘' },
      ],
      example: { fr: '雨傘を持ってきて。', zh: '把雨傘帶來。' },
    },
    思い出: {
      demo: true,
      word: '思い出',
      lemma: '思い出',
      ipa: 'おもいで',
      pos: 'n',
      gender: '',
      glossZh: '回憶、記念',
      glossFr: '心に残る出来事',
      alchNoteZh: '「思」從心中「出」來，凝固成名詞。',
      firstAttested: {
        year: '平安',
        era: 'MidJ',
        form: '思ひ出',
        whereZh: '日本中古和文',
        sourceZh: '',
        author: '紫式部',
        work: '源氏物語',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_omoi',
          surface: '思い',
          kind: 'stem',
          meaningZh: '想、思念',
          meaningFr: '思う',
          origin: 'Native',
          originForm: '思ふ',
          noteZh: '和語。連用形 思い。',
        },
        {
          id: 'm_de',
          surface: '出',
          kind: 'root',
          meaningZh: '出來',
          meaningFr: '出る',
          origin: 'Native',
          originForm: '出づ',
          noteZh: '思い出す 的名詞形。',
        },
      ],
      path: [
        { era: 'OJ', lang: 'OJ', form: '思ひ出づ', glossZh: '想起' },
        { era: 'ModJ', lang: 'ModJ', form: '思い出す／思い出', glossZh: '想起／回憶' },
      ],
      example: { fr: '夏の思い出。', zh: '夏天的回憶。' },
    },
    図書館: {
      demo: true,
      word: '図書館',
      lemma: '図書館',
      ipa: 'としょかん',
      pos: 'n',
      gender: '',
      glossZh: '圖書館',
      glossFr: '本を収める建物',
      alchNoteZh: '「圖書」入「館」：書之殿堂。漢語合劑。',
      firstAttested: {
        year: '明治',
        era: 'ModJ',
        form: '図書館',
        whereZh: '日本明治時期書面語',
        sourceZh: '',
        author: '',
        work: '',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_tosho',
          surface: '図書',
          kind: 'cf',
          meaningZh: '圖書、書籍',
          meaningFr: 'としょ',
          origin: 'Sino',
          originForm: '圖書',
          noteZh: '漢語。音讀。',
        },
        {
          id: 'm_kan',
          surface: '館',
          kind: 'han',
          meaningZh: '館、殿堂',
          meaningFr: 'かん',
          origin: 'Sino',
          originForm: '館',
          noteZh: '漢語接尾，表大型公共建築。',
        },
      ],
      path: [
        { era: 'Ch', lang: 'Ch', form: '圖書／館', glossZh: '書籍／館舍' },
        { era: 'ModJ', lang: 'ModJ', form: '図書館', glossZh: '圖書館' },
      ],
      example: { fr: '図書館で待つ。', zh: '在圖書館等。' },
    },
    取り消す: {
      demo: true,
      word: '取り消す',
      lemma: '取り消す',
      ipa: 'とりけす',
      pos: 'v',
      gender: '',
      glossZh: '取消、撤銷',
      glossFr: 'いったんしたことを無かったことにする',
      alchNoteZh: '「取」而「消」之：把已成之事抹去。',
      firstAttested: {
        year: '中世',
        era: 'MidJ',
        form: '取り消す',
        whereZh: '日本中世文獻',
        sourceZh: '',
        author: '',
        work: '',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_tori',
          surface: '取り',
          kind: 'pfx',
          meaningZh: '取、動作加強',
          meaningFr: '取る',
          origin: 'Native',
          originForm: '取る',
          noteZh: '和語接頭。連用形 取り。',
        },
        {
          id: 'm_kesu',
          surface: '消す',
          kind: 'root',
          meaningZh: '消去',
          meaningFr: '消す',
          origin: 'Native',
          originForm: '消す',
          noteZh: '五段動詞。',
        },
      ],
      path: [
        { era: 'MidJ', lang: 'MidJ', form: '取り消す', glossZh: '取消' },
        { era: 'ModJ', lang: 'ModJ', form: '取り消す', glossZh: '取消、撤銷' },
      ],
      example: { fr: '予約を取り消す。', zh: '取消預約。' },
    },
    今日: {
      demo: true,
      word: '今日',
      lemma: '今日',
      ipa: 'きょう',
      pos: 'n',
      gender: '',
      glossZh: '今天',
      glossFr: 'この日',
      alchNoteZh: '「今」之「日」焊成一詞，音讀 きょう。',
      firstAttested: {
        year: '上代',
        era: 'OJ',
        form: 'けふ',
        whereZh: '日本上代文獻',
        sourceZh: '',
        author: '',
        work: '万葉集',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_kon',
          surface: '今',
          kind: 'han',
          meaningZh: '現在、此刻',
          meaningFr: 'いま／こん',
          origin: 'Sino',
          originForm: '今',
          noteZh: '此處音讀，與訓讀 いま 不同爐。',
        },
        {
          id: 'm_nichi',
          surface: '日',
          kind: 'han',
          meaningZh: '日、白天',
          meaningFr: 'ひ／にち',
          origin: 'Sino',
          originForm: '日',
          noteZh: '音讀與 今 合成 きょう（特殊音變）。',
        },
      ],
      path: [
        { era: 'Ch', lang: 'Ch', form: '今日', glossZh: '今天' },
        { era: 'OJ', lang: 'OJ', form: 'けふ', glossZh: '今天' },
        { era: 'ModJ', lang: 'ModJ', form: '今日（きょう）', glossZh: '今天' },
      ],
      example: { fr: '今日は雨だ。', zh: '今天下雨。' },
    },
  };

  const EXPANDS = {
    '信じられない|信じ|derive': {
      op: 'derive',
      seed: '信じ',
      items: [
        { word: '信じる', kind: 'base', pos: 'v', glossZh: '相信', linkZh: '辭書形', era: 'ModJ' },
        { word: '信仰', kind: 'learned', pos: 'n', glossZh: '信仰', linkZh: '漢語書面詞', era: 'ModJ' },
        { word: '信用', kind: 'learned', pos: 'n', glossZh: '信用', linkZh: '漢語', era: 'ModJ' },
        { word: '確信', kind: 'learned', pos: 'n', glossZh: '確信', linkZh: '漢語', era: 'ModJ' },
      ],
    },
    '信じられない|ない|derive': {
      op: 'derive',
      seed: 'ない',
      items: [
        { word: '知らない', kind: 'derived', pos: 'v', glossZh: '不知道', linkZh: '同一否定', era: 'ModJ' },
        { word: 'できない', kind: 'derived', pos: 'v', glossZh: '不能', linkZh: '可能＋否定', era: 'ModJ' },
        { word: '見えない', kind: 'derived', pos: 'v', glossZh: '看不見', linkZh: '見える＋ない', era: 'ModJ' },
      ],
    },
    '雨傘|雨|compound': {
      op: 'compound',
      seed: '雨',
      items: [
        { word: '雨傘', kind: 'compound', pos: 'n', glossZh: '雨傘', linkZh: '本詞', era: 'ModJ' },
        { word: '雨雲', kind: 'compound', pos: 'n', glossZh: '雨雲', linkZh: '雨＋雲', era: 'ModJ' },
        { word: '雨宿り', kind: 'compound', pos: 'n', glossZh: '躲雨', linkZh: '雨＋宿り', era: 'ModJ' },
        { word: '大雨', kind: 'compound', pos: 'n', glossZh: '大雨', linkZh: '大＋雨', era: 'ModJ' },
      ],
    },
    '雨傘|傘|derive': {
      op: 'derive',
      seed: '傘',
      items: [
        { word: '傘', kind: 'base', pos: 'n', glossZh: '傘', linkZh: '詞根', era: 'ModJ' },
        { word: '日傘', kind: 'compound', pos: 'n', glossZh: '陽傘', linkZh: '日＋傘', era: 'ModJ' },
        { word: '傘立て', kind: 'compound', pos: 'n', glossZh: '傘架', linkZh: '傘＋立て', era: 'ModJ' },
      ],
    },
    '思い出|思い|derive': {
      op: 'derive',
      seed: '思い',
      items: [
        { word: '思う', kind: 'base', pos: 'v', glossZh: '想、認為', linkZh: '辭書形', era: 'ModJ' },
        { word: '思い出す', kind: 'derived', pos: 'v', glossZh: '想起', linkZh: '思い＋出す', era: 'ModJ' },
        { word: '思い切る', kind: 'derived', pos: 'v', glossZh: '下決心', linkZh: '思い＋切る', era: 'ModJ' },
        { word: '思案', kind: 'learned', pos: 'n', glossZh: '思量', linkZh: '漢語', era: 'ModJ' },
      ],
    },
    '図書館|図書|derive': {
      op: 'derive',
      seed: '図書',
      items: [
        { word: '図書', kind: 'base', pos: 'n', glossZh: '圖書', linkZh: '漢語', era: 'ModJ' },
        { word: '図書館', kind: 'compound', pos: 'n', glossZh: '圖書館', linkZh: '本詞', era: 'ModJ' },
        { word: '図書室', kind: 'compound', pos: 'n', glossZh: '圖書室', linkZh: '図書＋室', era: 'ModJ' },
      ],
    },
    '図書館|館|compound': {
      op: 'compound',
      seed: '館',
      items: [
        { word: '図書館', kind: 'compound', pos: 'n', glossZh: '圖書館', linkZh: '本詞', era: 'ModJ' },
        { word: '博物館', kind: 'compound', pos: 'n', glossZh: '博物館', linkZh: '博物＋館', era: 'ModJ' },
        { word: '美術館', kind: 'compound', pos: 'n', glossZh: '美術館', linkZh: '美術＋館', era: 'ModJ' },
        { word: '旅館', kind: 'compound', pos: 'n', glossZh: '旅館', linkZh: '旅＋館', era: 'ModJ' },
      ],
    },
    '取り消す|消す|derive': {
      op: 'derive',
      seed: '消す',
      items: [
        { word: '消す', kind: 'base', pos: 'v', glossZh: '消去', linkZh: '詞根動詞', era: 'ModJ' },
        { word: '消しゴム', kind: 'compound', pos: 'n', glossZh: '橡皮擦', linkZh: '消し＋ゴム', era: 'ModJ' },
        { word: '消化', kind: 'learned', pos: 'n', glossZh: '消化', linkZh: '漢語', era: 'ModJ' },
        { word: '消滅', kind: 'learned', pos: 'n', glossZh: '消滅', linkZh: '漢語', era: 'ModJ' },
      ],
    },
    '今日|日|compound': {
      op: 'compound',
      seed: '日',
      items: [
        { word: '今日', kind: 'compound', pos: 'n', glossZh: '今天', linkZh: '本詞', era: 'ModJ' },
        { word: '明日', kind: 'compound', pos: 'n', glossZh: '明天', linkZh: '明＋日', era: 'ModJ' },
        { word: '昨日', kind: 'compound', pos: 'n', glossZh: '昨天', linkZh: '昨＋日', era: 'ModJ' },
        { word: '毎日', kind: 'compound', pos: 'n', glossZh: '每天', linkZh: '毎＋日', era: 'ModJ' },
      ],
    },
    '今日|今|derive': {
      op: 'derive',
      seed: '今',
      items: [
        { word: '今', kind: 'base', pos: 'n', glossZh: '現在', linkZh: '訓讀 いま', era: 'ModJ' },
        { word: '今回', kind: 'compound', pos: 'n', glossZh: '這一次', linkZh: '今＋回', era: 'ModJ' },
        { word: '今後', kind: 'compound', pos: 'n', glossZh: '今後', linkZh: '今＋後', era: 'ModJ' },
        { word: '今日', kind: 'compound', pos: 'n', glossZh: '今天', linkZh: '本詞', era: 'ModJ' },
      ],
    },
  };

  const EXAMPLES = [
    { word: '信じられない', gloss: '難以置信' },
    { word: '雨傘', gloss: '雨傘' },
    { word: '思い出', gloss: '回憶' },
    { word: '図書館', gloss: '圖書館' },
    { word: '取り消す', gloss: '取消' },
    { word: '今日', gloss: '今天' },
  ];

  const COMBINES = {
    '雨|傘': {
      items: [
        { word: '雨傘', kind: 'compound', pos: 'n', glossZh: '雨傘', linkZh: '雨＋傘', era: 'ModJ' },
      ],
    },
    '日|傘': {
      items: [
        { word: '日傘', kind: 'compound', pos: 'n', glossZh: '陽傘', linkZh: '日＋傘', era: 'ModJ' },
      ],
    },
    '図書|館': {
      items: [
        { word: '図書館', kind: 'compound', pos: 'n', glossZh: '圖書館', linkZh: '図書＋館', era: 'ModJ' },
      ],
    },
    '今|日': {
      items: [
        { word: '今日', kind: 'compound', pos: 'n', glossZh: '今天', linkZh: '今＋日', era: 'ModJ' },
      ],
    },
  };

  if (VA.demo && VA.demo.register) {
    VA.demo.register('ja', { ANALYSES, EXPANDS, COMBINES, EXAMPLES });
  }
})(typeof window !== 'undefined' ? window : globalThis);
