(function (global) {
  const VA = (global.VerbaAthanor = global.VerbaAthanor || {});

  const ANALYSES = {
    unbelievable: {
      demo: true,
      word: 'unbelievable',
      lemma: 'unbelievable',
      ipa: '/ˌʌn.bɪˈliː.və.bəl/',
      pos: 'adj',
      gender: '',
      glossZh: '難以置信的',
      glossFr: 'impossible to believe',
      alchNoteZh: '否定覆上「相信」，再以 -able 定形：無法被相信的。',
      firstAttested: {
        year: '16c',
        era: 'EModE',
        form: 'unbelievable',
        whereZh: '英國，早期現代英語書面語',
        sourceZh: 'OED',
        author: '',
        work: '',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_un',
          surface: 'un-',
          kind: 'pfx',
          meaningZh: '否定、相反',
          meaningFr: 'not, opposite of',
          origin: 'OE',
          originForm: 'un-',
          originPath: 'PGmc *un- → OE un- → ModE un-',
          noteZh: '古英語否定前綴，與拉丁 in- 常成對出現。',
        },
        {
          id: 'm_believe',
          surface: 'believe',
          kind: 'root',
          meaningZh: '相信',
          meaningFr: 'to believe',
          origin: 'OE',
          originForm: 'gelȳfan',
          originPath: 'PGmc *ga-laubjan → OE gelȳfan → ME beleven → ModE believe',
          noteZh: '日耳曼通俗詞。書面雙重詞見 credible、credit。',
        },
        {
          id: 'm_able',
          surface: '-able',
          kind: 'sfx',
          meaningZh: '可被…的',
          meaningFr: 'that can be',
          origin: 'Lat',
          originForm: '-abilis',
          noteZh: '經古法語進入英語，把動詞煉成被動可能形容詞。',
        },
      ],
      path: [
        {
          era: 'PGmc',
          lang: 'PGmc',
          form: '*ga-laubjan',
          glossZh: '相信、視為親愛（存疑構擬）',
          via: 'reconstruct',
          noteZh: '原始日耳曼通行構擬：ga- 完成前綴 + laub-「親愛／信任」。',
          certainty: 'reconstructed',
        },
        {
          era: 'OE',
          lang: 'OE',
          form: 'gelȳfan',
          glossZh: '相信',
          via: 'inherit',
          noteZh: '古英語 gelȳfan／geliefan。ge- 後來在中古英語脫落或改寫。',
          certainty: 'certain',
        },
        {
          era: 'ME',
          lang: 'ME',
          form: 'beleven',
          glossZh: '相信',
          via: 'popular',
          noteZh: '中古英語 beleven：be- 前綴取代 ge-，元音與詞尾簡化。',
          certainty: 'certain',
        },
        {
          era: 'EModE',
          lang: 'EModE',
          form: 'believe',
          glossZh: '相信',
          via: 'inherit',
          noteZh: '早期現代英語拼寫靠近 believe；書面雙重詞 credible 另走拉丁線。',
          certainty: 'certain',
        },
        {
          era: 'ModE',
          lang: 'ModE',
          form: 'believe',
          glossZh: '相信',
          via: 'inherit',
          noteZh: '現代英語定形。',
          certainty: 'certain',
        },
        {
          era: 'ModE',
          lang: 'ModE',
          form: 'unbelievable',
          glossZh: '難以置信的',
          via: 'inherit',
          noteZh: 'un- 否定 + believe + -able（← 拉丁 -abilis，經法語）。',
          certainty: 'certain',
        },
      ],
      example: { fr: "That's unbelievable.", zh: '那真是難以置信。' },
    },
    sunflower: {
      demo: true,
      word: 'sunflower',
      lemma: 'sunflower',
      ipa: '/ˈsʌnˌflaʊ.ə/',
      pos: 'n',
      gender: '',
      glossZh: '向日葵',
      glossFr: 'a tall plant with a large yellow flower',
      alchNoteZh: '「太陽」與「花」合劑：轉向太陽的花。',
      firstAttested: {
        year: '1597',
        era: 'EModE',
        form: 'sunflower',
        whereZh: '英國書面語',
        sourceZh: 'OED',
        author: 'John Gerard',
        work: 'The Herball',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_sun',
          surface: 'sun',
          kind: 'root',
          meaningZh: '太陽',
          meaningFr: 'sun',
          origin: 'OE',
          originForm: 'sunne',
          noteZh: '古英語 sunne。',
        },
        {
          id: 'm_flower',
          surface: 'flower',
          kind: 'root',
          meaningZh: '花',
          meaningFr: 'flower',
          origin: 'OF',
          originForm: 'flour',
          noteZh: '經古法語 flour < 拉丁 flos。英語原生詞是 blossom。',
        },
      ],
      path: [
        { era: 'OE', lang: 'OE', form: 'sunne', glossZh: '太陽' },
        { era: 'OF', lang: 'OF', form: 'flour', glossZh: '花' },
        { era: 'ModE', lang: 'ModE', form: 'sunflower', glossZh: '向日葵（16 世紀合劑）' },
      ],
      example: { fr: 'Sunflowers turn toward the light.', zh: '向日葵會轉向光。' },
    },
    remember: {
      demo: true,
      word: 'remember',
      lemma: 'remember',
      ipa: '/rɪˈmem.bə/',
      pos: 'v',
      gender: '',
      glossZh: '記得、回想起',
      glossFr: 'to bring back to mind',
      alchNoteZh: '「再一次」把「記得」喚回心上。',
      firstAttested: {
        year: '14c',
        era: 'ME',
        form: 'remembren',
        whereZh: '中古英語文獻',
        sourceZh: 'OED',
        author: '',
        work: '',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_re',
          surface: 're-',
          kind: 'pfx',
          meaningZh: '再、回',
          meaningFr: 'again, back',
          origin: 'Lat',
          originForm: 're-',
          noteZh: '拉丁前綴，經法語進入英語。',
        },
        {
          id: 'm_member',
          surface: 'member',
          kind: 'root',
          meaningZh: '記得、銘記',
          meaningFr: 'mindful, remembering',
          origin: 'Lat',
          originForm: 'memor',
          noteZh: '拉丁 memor「記得的」。與 memory、memoir 同爐。',
        },
      ],
      path: [
        { era: 'Lat', lang: 'Lat', form: 'rememorari', glossZh: '再次記起' },
        { era: 'OF', lang: 'OF', form: 'remembrer', glossZh: '記得' },
        { era: 'ME', lang: 'ME', form: 'remembren', glossZh: '記得' },
        { era: 'ModE', lang: 'ModE', form: 'remember', glossZh: '記得' },
      ],
      example: { fr: 'I cannot remember his name.', zh: '我想不起他的名字。' },
    },
    bookshelf: {
      demo: true,
      word: 'bookshelf',
      lemma: 'bookshelf',
      ipa: '/ˈbʊk.ʃelf/',
      pos: 'n',
      gender: '',
      glossZh: '書架',
      glossFr: 'a shelf for holding books',
      alchNoteZh: '「書」與「架子」合劑：放書的橫木。',
      firstAttested: {
        year: '1818',
        era: 'ModE',
        form: 'book-shelf',
        whereZh: '英國書面語',
        sourceZh: 'OED',
        author: '',
        work: '',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_book',
          surface: 'book',
          kind: 'root',
          meaningZh: '書',
          meaningFr: 'book',
          origin: 'OE',
          originForm: 'bōc',
          noteZh: '古英語 bōc，本與山毛櫸木有關（刻寫材料）。',
        },
        {
          id: 'm_shelf',
          surface: 'shelf',
          kind: 'root',
          meaningZh: '架子、擱板',
          meaningFr: 'shelf',
          origin: 'OE',
          originForm: 'scylfe',
          noteZh: '日耳曼詞，指突出的板。',
        },
      ],
      path: [
        { era: 'OE', lang: 'OE', form: 'bōc', glossZh: '書、文書' },
        { era: 'OE', lang: 'OE', form: 'scylfe', glossZh: '擱板' },
        { era: 'ModE', lang: 'ModE', form: 'bookshelf', glossZh: '書架' },
      ],
      example: { fr: 'The novel is on the bookshelf.', zh: '那本小說在書架上。' },
    },
    undo: {
      demo: true,
      word: 'undo',
      lemma: 'undo',
      ipa: '/ʌnˈduː/',
      pos: 'v',
      gender: '',
      glossZh: '解開；撤銷',
      glossFr: 'to reverse what was done',
      alchNoteZh: '反向作用在「做」之根上：把已成之事還原。',
      firstAttested: {
        year: '',
        era: 'OE',
        form: 'undōn',
        whereZh: '古英語文獻',
        sourceZh: 'OED',
        author: '',
        work: '',
        certainty: 'certain',
      },
      morphemes: [
        {
          id: 'm_un2',
          surface: 'un-',
          kind: 'pfx',
          meaningZh: '反向、解除',
          meaningFr: 'reversal',
          origin: 'OE',
          originForm: 'un-',
          noteZh: '動詞前的 un- 表「解開、反向」，與形容詞 un-「否定」同源而用法不同。',
        },
        {
          id: 'm_do',
          surface: 'do',
          kind: 'root',
          meaningZh: '做',
          meaningFr: 'to do',
          origin: 'OE',
          originForm: 'dōn',
          noteZh: '古英語 dōn。書面詞見 fact、factory。',
        },
      ],
      path: [
        { era: 'PIE', lang: 'PIE', form: '*dʰeh₁-', glossZh: '放置、做（存疑構擬）' },
        { era: 'OE', lang: 'OE', form: 'dōn / undōn', glossZh: '做／解開' },
        { era: 'ModE', lang: 'ModE', form: 'undo', glossZh: '解開；撤銷' },
      ],
      example: { fr: 'Undo the knot.', zh: '把結解開。' },
    },
    today: {
      demo: true,
      word: 'today',
      lemma: 'today',
      ipa: '/təˈdeɪ/',
      pos: 'adv',
      gender: '',
      glossZh: '今天',
      glossFr: 'on this day',
      alchNoteZh: '「到這一日」凝固成一個詞，像把兩塊金屬焊在一起。',
      firstAttested: {
        year: '',
        era: 'OE',
        form: 'tō dæge',
        whereZh: '古英語文獻',
        sourceZh: 'OED',
        author: '',
        work: '',
        certainty: 'certain',
      },
      morphemes: [
        {
          id: 'm_to',
          surface: 'to',
          kind: 'pfx',
          meaningZh: '到、在',
          meaningFr: 'to, at',
          origin: 'OE',
          originForm: 'tō',
          noteZh: '介詞凝固成前綴。',
        },
        {
          id: 'm_day',
          surface: 'day',
          kind: 'root',
          meaningZh: '日、白天',
          meaningFr: 'day',
          origin: 'OE',
          originForm: 'dæg',
          noteZh: '古英語 dæg。',
        },
      ],
      path: [
        { era: 'OE', lang: 'OE', form: 'tō dæge', glossZh: '在這一日' },
        { era: 'ME', lang: 'ME', form: 'to day', glossZh: '今天' },
        { era: 'ModE', lang: 'ModE', form: 'today', glossZh: '今天' },
      ],
      example: { fr: 'Today it is raining.', zh: '今天下雨。' },
    },
  };

  const EXPANDS = {
    'unbelievable|believe|distill': {
      op: 'distill',
      seed: 'believe',
      items: [
        { word: 'believe', kind: 'base', pos: 'v', glossZh: '相信', linkZh: '現代動詞', era: 'ModE' },
        { word: 'gelȳfan', kind: 'root', pos: 'v', glossZh: '相信', linkZh: '古英語原質', era: 'OE' },
        { word: '*ga-laubjan', kind: 'root', pos: '', glossZh: '相信（存疑）', linkZh: 'PGmc 構擬', era: 'PGmc' },
      ],
    },
    'unbelievable|believe|derive': {
      op: 'derive',
      seed: 'believe',
      items: [
        { word: 'believe', kind: 'base', pos: 'v', glossZh: '相信', linkZh: '通俗動詞', era: 'ModE' },
        { word: 'belief', kind: 'derived', pos: 'n', glossZh: '信念', linkZh: '通俗名詞', era: 'ModE' },
        { word: 'believer', kind: 'derived', pos: 'n', glossZh: '信徒、相信者', linkZh: '行為者', era: 'ModE' },
        { word: 'credible', kind: 'learned', pos: 'adj', glossZh: '可信的', linkZh: '書面拉丁雙重詞', era: 'ModE' },
        { word: 'credit', kind: 'learned', pos: 'n', glossZh: '信用', linkZh: '書面詞', era: 'ModE' },
      ],
    },
    'unbelievable|un-|derive': {
      op: 'derive',
      seed: 'un-',
      items: [
        { word: 'unknown', kind: 'derived', pos: 'adj', glossZh: '未知的', linkZh: '同一否定前綴', era: 'ModE' },
        { word: 'unfair', kind: 'derived', pos: 'adj', glossZh: '不公平的', linkZh: 'un- + fair', era: 'ModE' },
        { word: 'unable', kind: 'derived', pos: 'adj', glossZh: '不能的', linkZh: 'un- + able', era: 'ModE' },
        { word: 'unhappy', kind: 'derived', pos: 'adj', glossZh: '不快樂的', linkZh: 'un- + happy', era: 'ModE' },
      ],
    },
    'unbelievable|-able|derive': {
      op: 'derive',
      seed: '-able',
      items: [
        { word: 'readable', kind: 'derived', pos: 'adj', glossZh: '可讀的', linkZh: 'read + -able', era: 'ModE' },
        { word: 'portable', kind: 'derived', pos: 'adj', glossZh: '可攜的', linkZh: 'port + -able', era: 'ModE' },
        { word: 'lovable', kind: 'derived', pos: 'adj', glossZh: '可愛的', linkZh: 'love + -able', era: 'ModE' },
        { word: 'possible', kind: 'learned', pos: 'adj', glossZh: '可能的', linkZh: '異形 -ible', era: 'ModE' },
      ],
    },
    'sunflower|sun|derive': {
      op: 'derive',
      seed: 'sun',
      items: [
        { word: 'sun', kind: 'base', pos: 'n', glossZh: '太陽', linkZh: '詞根', era: 'ModE' },
        { word: 'sunny', kind: 'derived', pos: 'adj', glossZh: '晴朗的', linkZh: 'sun + -y', era: 'ModE' },
        { word: 'sunrise', kind: 'compound', pos: 'n', glossZh: '日出', linkZh: 'sun + rise', era: 'ModE' },
        { word: 'sunlight', kind: 'compound', pos: 'n', glossZh: '日光', linkZh: 'sun + light', era: 'ModE' },
      ],
    },
    'sunflower|sun|compound': {
      op: 'compound',
      seed: 'sun',
      items: [
        { word: 'sunflower', kind: 'compound', pos: 'n', glossZh: '向日葵', linkZh: '本詞', era: 'ModE' },
        { word: 'sunshine', kind: 'compound', pos: 'n', glossZh: '陽光', linkZh: 'sun + shine', era: 'ModE' },
        { word: 'sunburn', kind: 'compound', pos: 'n', glossZh: '曬傷', linkZh: 'sun + burn', era: 'ModE' },
        { word: 'sunset', kind: 'compound', pos: 'n', glossZh: '日落', linkZh: 'sun + set', era: 'ModE' },
      ],
    },
    'sunflower|flower|derive': {
      op: 'derive',
      seed: 'flower',
      items: [
        { word: 'flower', kind: 'base', pos: 'n', glossZh: '花', linkZh: '詞根', era: 'ModE' },
        { word: 'floral', kind: 'learned', pos: 'adj', glossZh: '花的', linkZh: '拉丁 flos 書面詞', era: 'ModE' },
        { word: 'flourish', kind: 'derived', pos: 'v', glossZh: '繁盛', linkZh: '花開 → 興旺', era: 'ModE' },
        { word: 'blossom', kind: 'native', pos: 'n', glossZh: '花朵（原生詞）', linkZh: '日耳曼對應詞', era: 'ModE' },
      ],
    },
    'remember|member|distill': {
      op: 'distill',
      seed: 'member',
      items: [
        { word: 'memory', kind: 'derived', pos: 'n', glossZh: '記憶', linkZh: '同一 memor 根', era: 'ModE' },
        { word: 'memor', kind: 'root', pos: 'adj', glossZh: '記得的', linkZh: '拉丁原質', era: 'Lat' },
      ],
    },
    'remember|member|derive': {
      op: 'derive',
      seed: 'member',
      items: [
        { word: 'memory', kind: 'derived', pos: 'n', glossZh: '記憶', linkZh: '同一詞根', era: 'ModE' },
        { word: 'memorial', kind: 'derived', pos: 'n', glossZh: '紀念物', linkZh: 'memor + -ial', era: 'ModE' },
        { word: 'memoir', kind: 'derived', pos: 'n', glossZh: '回憶錄', linkZh: '經法語', era: 'ModE' },
        { word: 'memorable', kind: 'derived', pos: 'adj', glossZh: '難忘的', linkZh: 'memor + -able', era: 'ModE' },
      ],
    },
    'remember|re-|derive': {
      op: 'derive',
      seed: 're-',
      items: [
        { word: 'return', kind: 'derived', pos: 'v', glossZh: '返回', linkZh: 're- + turn', era: 'ModE' },
        { word: 'rewrite', kind: 'derived', pos: 'v', glossZh: '重寫', linkZh: 're- + write', era: 'ModE' },
        { word: 'recall', kind: 'derived', pos: 'v', glossZh: '回想', linkZh: 're- + call', era: 'ModE' },
        { word: 'rebuild', kind: 'derived', pos: 'v', glossZh: '重建', linkZh: 're- + build', era: 'ModE' },
      ],
    },
    'bookshelf|book|compound': {
      op: 'compound',
      seed: 'book',
      items: [
        { word: 'bookshelf', kind: 'compound', pos: 'n', glossZh: '書架', linkZh: '本詞', era: 'ModE' },
        { word: 'bookmark', kind: 'compound', pos: 'n', glossZh: '書籤', linkZh: 'book + mark', era: 'ModE' },
        { word: 'bookstore', kind: 'compound', pos: 'n', glossZh: '書店', linkZh: 'book + store', era: 'ModE' },
        { word: 'notebook', kind: 'compound', pos: 'n', glossZh: '筆記本', linkZh: 'note + book', era: 'ModE' },
      ],
    },
    'bookshelf|book|derive': {
      op: 'derive',
      seed: 'book',
      items: [
        { word: 'book', kind: 'base', pos: 'n', glossZh: '書', linkZh: '詞根', era: 'ModE' },
        { word: 'bookish', kind: 'derived', pos: 'adj', glossZh: '書卷氣的', linkZh: 'book + -ish', era: 'ModE' },
        { word: 'booklet', kind: 'derived', pos: 'n', glossZh: '小冊子', linkZh: 'book + -let', era: 'ModE' },
      ],
    },
    'undo|do|distill': {
      op: 'distill',
      seed: 'do',
      items: [
        { word: 'do', kind: 'base', pos: 'v', glossZh: '做', linkZh: '現代動詞', era: 'ModE' },
        { word: 'dōn', kind: 'root', pos: 'v', glossZh: '做', linkZh: '古英語原質', era: 'OE' },
        { word: '*dʰeh₁-', kind: 'root', pos: '', glossZh: '放置、做（存疑）', linkZh: 'PIE 構擬', era: 'PIE' },
      ],
    },
    'undo|do|derive': {
      op: 'derive',
      seed: 'do',
      items: [
        { word: 'do', kind: 'base', pos: 'v', glossZh: '做', linkZh: '詞根動詞', era: 'ModE' },
        { word: 'deed', kind: 'derived', pos: 'n', glossZh: '行為', linkZh: '同一日耳曼根的名詞', era: 'ModE' },
        { word: 'fact', kind: 'learned', pos: 'n', glossZh: '事實', linkZh: '拉丁 facere 書面詞', era: 'ModE' },
        { word: 'factory', kind: 'learned', pos: 'n', glossZh: '工廠', linkZh: '做之處', era: 'ModE' },
      ],
    },
    'undo|un-|derive': {
      op: 'derive',
      seed: 'un-',
      items: [
        { word: 'undo', kind: 'derived', pos: 'v', glossZh: '解開', linkZh: '本詞', era: 'ModE' },
        { word: 'unlock', kind: 'derived', pos: 'v', glossZh: '解鎖', linkZh: 'un- + lock', era: 'ModE' },
        { word: 'untie', kind: 'derived', pos: 'v', glossZh: '解開（繩）', linkZh: 'un- + tie', era: 'ModE' },
        { word: 'unpack', kind: 'derived', pos: 'v', glossZh: '拆箱', linkZh: 'un- + pack', era: 'ModE' },
      ],
    },
    'today|day|derive': {
      op: 'derive',
      seed: 'day',
      items: [
        { word: 'day', kind: 'base', pos: 'n', glossZh: '日', linkZh: '詞根', era: 'ModE' },
        { word: 'daily', kind: 'derived', pos: 'adj', glossZh: '每日的', linkZh: 'day + -ly', era: 'ModE' },
        { word: 'today', kind: 'compound', pos: 'adv', glossZh: '今天', linkZh: '本詞', era: 'ModE' },
        { word: 'yesterday', kind: 'compound', pos: 'n', glossZh: '昨天', linkZh: 'yester + day', era: 'ModE' },
      ],
    },
    'today|day|compound': {
      op: 'compound',
      seed: 'day',
      items: [
        { word: 'today', kind: 'compound', pos: 'adv', glossZh: '今天', linkZh: 'to + day', era: 'ModE' },
        { word: 'birthday', kind: 'compound', pos: 'n', glossZh: '生日', linkZh: 'birth + day', era: 'ModE' },
        { word: 'daylight', kind: 'compound', pos: 'n', glossZh: '日光', linkZh: 'day + light', era: 'ModE' },
        { word: 'daydream', kind: 'compound', pos: 'n', glossZh: '白日夢', linkZh: 'day + dream', era: 'ModE' },
      ],
    },
    'today|day|distill': {
      op: 'distill',
      seed: 'day',
      items: [
        { word: 'day', kind: 'base', pos: 'n', glossZh: '日', linkZh: '現代英語', era: 'ModE' },
        { word: 'dæg', kind: 'root', pos: 'n', glossZh: '日', linkZh: '古英語原質', era: 'OE' },
      ],
    },
  };

  const EXAMPLES = [
    { word: 'unbelievable', gloss: '難以置信' },
    { word: 'sunflower', gloss: '向日葵' },
    { word: 'remember', gloss: '記得' },
    { word: 'bookshelf', gloss: '書架' },
    { word: 'undo', gloss: '解開' },
    { word: 'today', gloss: '今天' },
  ];

  const COMBINES = {
    'sun|flower': {
      items: [
        { word: 'sunflower', kind: 'compound', pos: 'n', glossZh: '向日葵', linkZh: 'sun + flower', era: 'ModE' },
      ],
    },
    'sun|day': {
      items: [
        { word: 'Sunday', kind: 'compound', pos: 'n', glossZh: '星期日', linkZh: 'sun + day', era: 'ModE' },
        { word: 'sundial', kind: 'compound', pos: 'n', glossZh: '日晷', linkZh: 'sun + dial（day 的日光義）', era: 'ModE' },
      ],
    },
    'book|shelf': {
      items: [
        { word: 'bookshelf', kind: 'compound', pos: 'n', glossZh: '書架', linkZh: 'book + shelf', era: 'ModE' },
      ],
    },
    'to|day': {
      items: [
        { word: 'today', kind: 'compound', pos: 'adv', glossZh: '今天', linkZh: 'to + day', era: 'ModE' },
      ],
    },
    'book|mark': {
      items: [
        { word: 'bookmark', kind: 'compound', pos: 'n', glossZh: '書籤', linkZh: 'book + mark', era: 'ModE' },
      ],
    },
  };

  if (VA.demo && VA.demo.register) {
    VA.demo.register('en', { ANALYSES, EXPANDS, COMBINES, EXAMPLES });
  }
})(typeof window !== 'undefined' ? window : globalThis);
