(function (global) {
  const VA = (global.VerbaAthanor = global.VerbaAthanor || {});

  const ANALYSES = {
    불가능: {
      demo: true,
      word: '불가능',
      lemma: '불가능',
      ipa: 'bulganeung',
      pos: 'n',
      gender: '',
      glossZh: '不可能',
      glossFr: '이루어질 수 없음',
      alchNoteZh: '「不」封住「可能」：成不了之事。漢語詞。',
      firstAttested: {
        year: '近代',
        era: 'MK',
        form: '불가능',
        whereZh: '近代韓語漢字詞',
        sourceZh: '',
        author: '',
        work: '',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_bul',
          surface: '불',
          kind: 'pfx',
          meaningZh: '否定',
          meaningFr: '아님',
          origin: 'Sino',
          originForm: '不',
          noteZh: '한자어 접두. Hanja 不。',
        },
        {
          id: 'm_ganeung',
          surface: '가능',
          kind: 'root',
          meaningZh: '可能',
          meaningFr: '가능함',
          origin: 'Sino',
          originForm: '可能',
          noteZh: '한자어. 가능／가능성 同爐。',
        },
      ],
      path: [
        { era: 'Ch', lang: 'Ch', form: '不可能', glossZh: '不可能' },
        { era: 'MK', lang: 'MK', form: '불가능', glossZh: '不可能' },
      ],
      example: { fr: '그건 불가능해.', zh: '那是不可能的。' },
    },
    우산: {
      demo: true,
      word: '우산',
      lemma: '우산',
      ipa: 'usan',
      pos: 'n',
      gender: '',
      glossZh: '雨傘',
      glossFr: '비를 막는 산',
      alchNoteZh: '「雨」與「傘」合劑：擋雨之蓋。',
      firstAttested: {
        year: '朝鮮',
        era: 'MK',
        form: '우산',
        whereZh: '韓語漢字詞（雨傘）',
        sourceZh: '',
        author: '',
        work: '',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_u',
          surface: '우',
          kind: 'han',
          meaningZh: '雨',
          meaningFr: '비',
          origin: 'Sino',
          originForm: '雨',
          noteZh: '한자어. Hanja 雨。',
        },
        {
          id: 'm_san',
          surface: '산',
          kind: 'han',
          meaningZh: '傘',
          meaningFr: '우산의 산',
          origin: 'Sino',
          originForm: '傘',
          noteZh: '한자어. Hanja 傘。與「山」同音異字。',
        },
      ],
      path: [
        { era: 'Ch', lang: 'Ch', form: '雨傘', glossZh: '雨傘' },
        { era: 'MK', lang: 'MK', form: '우산', glossZh: '雨傘' },
      ],
      example: { fr: '우산을 가져가.', zh: '把傘帶去。' },
    },
    추억: {
      demo: true,
      word: '추억',
      lemma: '추억',
      ipa: 'chueok',
      pos: 'n',
      gender: '',
      glossZh: '回憶',
      glossFr: '지난날을 떠올림',
      alchNoteZh: '「追」而「憶」之：把往事追回心上。',
      firstAttested: {
        year: '近代',
        era: 'MK',
        form: '추억',
        whereZh: '韓語漢字詞（追憶）',
        sourceZh: '',
        author: '',
        work: '',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_chu',
          surface: '추',
          kind: 'han',
          meaningZh: '追、回溯',
          meaningFr: '쫓다, 더듬다',
          origin: 'Sino',
          originForm: '追',
          noteZh: '한자어. Hanja 追。',
        },
        {
          id: 'm_eok',
          surface: '억',
          kind: 'han',
          meaningZh: '憶、記得',
          meaningFr: '기억하다',
          origin: 'Sino',
          originForm: '憶',
          noteZh: '한자어. Hanja 憶。',
        },
      ],
      path: [
        { era: 'Ch', lang: 'Ch', form: '追憶', glossZh: '追憶' },
        { era: 'MK', lang: 'MK', form: '추억', glossZh: '回憶' },
      ],
      example: { fr: '여름의 추억.', zh: '夏天的回憶。' },
    },
    도서관: {
      demo: true,
      word: '도서관',
      lemma: '도서관',
      ipa: 'doseogwan',
      pos: 'n',
      gender: '',
      glossZh: '圖書館',
      glossFr: '책을 모아 두는 곳',
      alchNoteZh: '「圖書」入「館」：書之殿堂。',
      firstAttested: {
        year: '近代',
        era: 'MK',
        form: '도서관',
        whereZh: '韓語漢字詞（圖書館）',
        sourceZh: '',
        author: '',
        work: '',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_doseo',
          surface: '도서',
          kind: 'cf',
          meaningZh: '圖書、書籍',
          meaningFr: '책',
          origin: 'Sino',
          originForm: '圖書',
          noteZh: '한자어.',
        },
        {
          id: 'm_gwan',
          surface: '관',
          kind: 'han',
          meaningZh: '館',
          meaningFr: '큰 건물',
          origin: 'Sino',
          originForm: '館',
          noteZh: '한자어 접미. 도서관·박물관.',
        },
      ],
      path: [
        { era: 'Ch', lang: 'Ch', form: '圖書館', glossZh: '圖書館' },
        { era: 'MK', lang: 'MK', form: '도서관', glossZh: '圖書館' },
      ],
      example: { fr: '도서관에서 만나.', zh: '在圖書館見。' },
    },
    취소하다: {
      demo: true,
      word: '취소하다',
      lemma: '취소하다',
      ipa: 'chwisolhada',
      pos: 'v',
      gender: '',
      glossZh: '取消',
      glossFr: '없던 일로 하다',
      alchNoteZh: '「取消」加上 하다：把已成之事抹去。',
      firstAttested: {
        year: '近代',
        era: 'MK',
        form: '취소하다',
        whereZh: '近代韓語漢字詞＋하다',
        sourceZh: '',
        author: '',
        work: '',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_chwiso',
          surface: '취소',
          kind: 'root',
          meaningZh: '取消',
          meaningFr: '취소',
          origin: 'Sino',
          originForm: '取消',
          noteZh: '한자어 명사 어근.',
        },
        {
          id: 'm_hada',
          surface: '하다',
          kind: 'infl',
          meaningZh: '做（動詞化）',
          meaningFr: '하다',
          origin: 'Native',
          originForm: '하다',
          noteZh: '고유어 동사화 접사.',
        },
      ],
      path: [
        { era: 'Ch', lang: 'Ch', form: '取消', glossZh: '取消' },
        { era: 'MK', lang: 'MK', form: '취소하다', glossZh: '取消' },
      ],
      example: { fr: '예약을 취소하다.', zh: '取消預約。' },
    },
    오늘: {
      demo: true,
      word: '오늘',
      lemma: '오늘',
      ipa: 'oneul',
      pos: 'n',
      gender: '',
      glossZh: '今天',
      glossFr: '이 날',
      alchNoteZh: '고유어，不宜硬拆音節。書面漢語對應是 금일。',
      firstAttested: {
        year: '中世',
        era: 'SK',
        form: '오늘',
        whereZh: '中世韓語固有語文獻',
        sourceZh: '',
        author: '',
        work: '',
        certainty: 'probable',
      },
      morphemes: [
        {
          id: 'm_oneul',
          surface: '오늘',
          kind: 'root',
          meaningZh: '今天',
          meaningFr: '오늘',
          origin: 'Native',
          originForm: '오늘',
          noteZh: '고유어 한 덩어리. 對應 한자어 금일（今日）。',
        },
      ],
      path: [
        { era: 'OK', lang: 'OK', form: '오늘', glossZh: '今天（固有語）' },
        { era: 'MK', lang: 'MK', form: '오늘', glossZh: '今天' },
      ],
      example: { fr: '오늘은 비가 온다.', zh: '今天下雨。' },
    },
  };

  const EXPANDS = {
    '불가능|불|derive': {
      op: 'derive',
      seed: '불',
      items: [
        { word: '불가능', kind: 'derived', pos: 'n', glossZh: '不可能', linkZh: '本詞', era: 'MK' },
        { word: '불만', kind: 'derived', pos: 'n', glossZh: '不滿', linkZh: '不＋滿', era: 'MK' },
        { word: '불안', kind: 'derived', pos: 'n', glossZh: '不安', linkZh: '不＋安', era: 'MK' },
        { word: '불편', kind: 'derived', pos: 'n', glossZh: '不便', linkZh: '不＋便', era: 'MK' },
      ],
    },
    '불가능|가능|derive': {
      op: 'derive',
      seed: '가능',
      items: [
        { word: '가능', kind: 'base', pos: 'n', glossZh: '可能', linkZh: '詞根', era: 'MK' },
        { word: '가능성', kind: 'derived', pos: 'n', glossZh: '可能性', linkZh: '가능＋성', era: 'MK' },
        { word: '불가능', kind: 'derived', pos: 'n', glossZh: '不可能', linkZh: '本詞', era: 'MK' },
      ],
    },
    '우산|우|compound': {
      op: 'compound',
      seed: '우',
      items: [
        { word: '우산', kind: 'compound', pos: 'n', glossZh: '雨傘', linkZh: '本詞', era: 'MK' },
        { word: '우비', kind: 'compound', pos: 'n', glossZh: '雨衣', linkZh: '雨＋備', era: 'MK' },
        { word: '우천', kind: 'compound', pos: 'n', glossZh: '雨天', linkZh: '雨＋天', era: 'MK' },
      ],
    },
    '추억|억|derive': {
      op: 'derive',
      seed: '억',
      items: [
        { word: '기억', kind: 'derived', pos: 'n', glossZh: '記憶', linkZh: '記＋憶', era: 'MK' },
        { word: '추억', kind: 'derived', pos: 'n', glossZh: '回憶', linkZh: '本詞', era: 'MK' },
        { word: '회억', kind: 'learned', pos: 'n', glossZh: '回憶（文）', linkZh: '回＋憶', era: 'MK' },
      ],
    },
    '도서관|도서|derive': {
      op: 'derive',
      seed: '도서',
      items: [
        { word: '도서', kind: 'base', pos: 'n', glossZh: '圖書', linkZh: '한자어', era: 'MK' },
        { word: '도서관', kind: 'compound', pos: 'n', glossZh: '圖書館', linkZh: '本詞', era: 'MK' },
        { word: '도서실', kind: 'compound', pos: 'n', glossZh: '圖書室', linkZh: '도서＋실', era: 'MK' },
      ],
    },
    '도서관|관|compound': {
      op: 'compound',
      seed: '관',
      items: [
        { word: '도서관', kind: 'compound', pos: 'n', glossZh: '圖書館', linkZh: '本詞', era: 'MK' },
        { word: '박물관', kind: 'compound', pos: 'n', glossZh: '博物館', linkZh: '博物＋館', era: 'MK' },
        { word: '미술관', kind: 'compound', pos: 'n', glossZh: '美術館', linkZh: '美術＋館', era: 'MK' },
        { word: '체육관', kind: 'compound', pos: 'n', glossZh: '體育館', linkZh: '體育＋館', era: 'MK' },
      ],
    },
    '취소하다|취소|derive': {
      op: 'derive',
      seed: '취소',
      items: [
        { word: '취소', kind: 'base', pos: 'n', glossZh: '取消', linkZh: '명사', era: 'MK' },
        { word: '취소하다', kind: 'derived', pos: 'v', glossZh: '取消', linkZh: '本詞', era: 'MK' },
        { word: '해지하다', kind: 'derived', pos: 'v', glossZh: '解約', linkZh: '近義', era: 'MK' },
      ],
    },
    '취소하다|하다|derive': {
      op: 'derive',
      seed: '하다',
      items: [
        { word: '공부하다', kind: 'derived', pos: 'v', glossZh: '學習', linkZh: '공부＋하다', era: 'MK' },
        { word: '시작하다', kind: 'derived', pos: 'v', glossZh: '開始', linkZh: '시작＋하다', era: 'MK' },
        { word: '생각하다', kind: 'derived', pos: 'v', glossZh: '思考', linkZh: '생각＋하다', era: 'MK' },
      ],
    },
    '오늘|오늘|derive': {
      op: 'derive',
      seed: '오늘',
      items: [
        { word: '오늘', kind: 'base', pos: 'n', glossZh: '今天', linkZh: '고유어', era: 'MK' },
        { word: '금일', kind: 'learned', pos: 'n', glossZh: '今日（文）', linkZh: '한자어 對應', era: 'MK' },
        { word: '어제', kind: 'native', pos: 'n', glossZh: '昨天', linkZh: '고유어 對立', era: 'MK' },
        { word: '내일', kind: 'native', pos: 'n', glossZh: '明天', linkZh: '고유어 對立', era: 'MK' },
      ],
    },
  };

  const EXAMPLES = [
    { word: '불가능', gloss: '不可能' },
    { word: '우산', gloss: '雨傘' },
    { word: '추억', gloss: '回憶' },
    { word: '도서관', gloss: '圖書館' },
    { word: '취소하다', gloss: '取消' },
    { word: '오늘', gloss: '今天' },
  ];

  const COMBINES = {
    '우|산': {
      items: [
        { word: '우산', kind: 'compound', pos: 'n', glossZh: '雨傘', linkZh: '우＋산', era: 'MK' },
      ],
    },
    '도서|관': {
      items: [
        { word: '도서관', kind: 'compound', pos: 'n', glossZh: '圖書館', linkZh: '도서＋관', era: 'MK' },
      ],
    },
  };

  if (VA.demo && VA.demo.register) {
    VA.demo.register('ko', { ANALYSES, EXPANDS, COMBINES, EXAMPLES });
  }
})(typeof window !== 'undefined' ? window : globalThis);
